# Generated by Django 6.0.6 on 2026-06-11 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlchecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheck',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
