# Generated by Django 6.0.6 on 2026-06-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlchecker', '0002_urlcheck_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheck',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='urlcheck',
            name='checked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
